<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<meta charset="UTF-8" />';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge" />';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0" />';
echo '<meta name="keywords" content="LeanBiome ,buy LeanBiome ,LeanBiome .com,LeanBiome  official" />';
echo '<meta name="description" content="LeanBiome  a popular blood sugar control supplement, contains unique ingredients that help users manage blood sugar levels. This blood sugar support formula is proven to improve overall health." />';
echo '<meta name="author" content="john" />';
echo '<meta name="msvalidate.01" content="6E6E7F3473195716FB7979716C5A4DD0" />';
echo '';
echo '<title>LeanBiome ™-Official Website</title>';
echo '<link rel="icon" type="image/x-jpg" href="./asset/Image/favicon.jpg" />';
echo '<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer"';
echo '/>';
echo '<link rel="stylesheet" href="./asset/css/style.css" />';
echo '</head>';
echo '';
echo '<body>';
echo '<nav class="navbar navbar-expand-lg navbar-light custom-bg-1 fs-5">';
echo '<div class="container">';
echo '<a class="navbar-brand fw-bold" href="#">';
echo 'LeanBiome ™';
echo '</a>';
echo '<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">';
echo '<span class="navbar-toggler-icon"></span>';
echo '</button>';
echo '<div class="collapse navbar-collapse" id="navbarTogglerDemo01">';
echo '<ul class="navbar-nav mb-2 mb-lg-0 ms-auto">';
echo '<li class="nav-item">';
echo '<a class="nav-link active p-3" aria-current="page" href="#LeanBiome ">How it Works?</a';
echo '>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link active p-3" href="#LeanBiome Ingredients"';
echo '>Ingredients</a';
echo '>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link active p-3" href="#LeanBiome Benifits"';
echo '>Benefits</a';
echo '>';
echo '</li>';
echo '<li class="nav-item mt-2 ms-2">';
echo '<a';
echo 'href="https://alxs7.bemobtrcks.com/go/2d85b103-980c-443f-bdbd-44206d6e511f"';
echo 'class="btn btn-warning py-2 px-3 fw-bold"';
echo '>Order Now</a';
echo '>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</nav>';
echo '';
echo '<div class="container-fluid custom-bg-0" id="LeanBiome supplement">';
echo '<span></span>';
echo '';
echo '<div class="container-sm bg-white">';
echo '<p class="text-center m-0 fw-blod fs-1">';
echo '</p>';
echo '<div class="custom-line"></div>';
echo '<h1 class="fw-blod text-center fs-1">';
echo 'LeanBiome ™ Official Website';
echo '</h1>';
echo '';
echo '<div class="row p-md-5">';
echo '<div class="col-md-6 custom-order">';
echo '<p class="fs-3">';
echo '<b>It's Time to Become Naturally Lean!</b><br><br>LeanBiome is a nutritional supplement for weight loss that is';
echo 'modern, sustainable, and environmentally friendly. Meghan S.';
echo 'founded Lean for Good and created the LeanBiome supplement.';
echo '</p>';
echo '<p class="fs-3">Regular Price: $129/per Bottle</p>';
echo '<p class="fw-bold fs-1">Only for: $39/per Bottle</p>';
echo '<a';
echo 'href="https://alxs7.bemobtrcks.com/go/2d85b103-980c-443f-bdbd-44206d6e511f"';
echo '>';
echo '<img';
echo 'src="./asset/Image/LeanBiomeBuyNow.gif"';
echo 'alt="LeanBiomeBuyNow"';
echo 'class="img-fluid"';
echo '/></a>';
echo '</div>';
echo '<div class="col-md-6 custom-order-1">';
echo '<a href="https://alxs7.bemobtrcks.com/go/2d85b103-980c-443f-bdbd-44206d6e511f">';
echo '<img';
echo 'src="./asset/Image/leanbiome.png"';
echo 'alt="LeanBiome "';
echo 'class="img-fluid"';
echo '/></a>';
echo '<img src="./asset/Image/LeanBiome-5-star.jpg" alt="LeanBiome -5-star" class="img-fluid" />';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '</div>';
echo '';
echo '';
echo '</p>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '';
echo '</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="container-fluid custom-bg-1 p-4 mt-2">';
echo '<div class="container custom-shadow p-3">';
echo '<div class="row">';
echo '<div class="col-md-4">';
echo '<a href="https://alxs7.bemobtrcks.com/go/2d85b103-980c-443f-bdbd-44206d6e511f">';
echo '<img';
echo 'src="./asset/Image/moneybackguarentee.png"';
echo 'alt="moneybackguarantee"';
echo 'class="img-fluid custom-width-1"';
echo '/></a>';
echo '</div>';
echo '<div class="col-md-8 text-center">';
echo '<p class="text-black fs-1 fw-bold">';
echo '180-DAYS 100% MONEY-BACK GUARANTEE';
echo '</p>';
echo '<p class="fs-4 text-white">';
echo 'I'm so confident you'll be head-over-heels thrilled with the results you get that I'm giving you a full six months to try LeanBiome for yourself, completely risk-free, regardless of the package you choose.';
echo '</p>';
echo '';
echo '<p class="fs-4 text-white">';
echo 'If you change your mind for any reason at all, simply contact my friendly customer support team, and they'll refund 100% of the purchase price, no questions asked.';
echo '</p>';
echo '<a href="https://alxs7.bemobtrcks.com/go/2d85b103-980c-443f-bdbd-44206d6e511f" class="btn btn-warning fs-4 rounded-3 fw-bold">Get your bottle and see for yourself</a';
echo '>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '</div>';
echo '';
echo '<div class="container-fluid custom-bg-2 text-center p-2 fw-bold">';
echo '<p class="text-white fs-1">Limited Time Special Pricing - Act Now!</p>';
echo '<p class="text-warning fs-3">';
echo 'Secure Your Reserved LeanBiome Bottle While Stocks Last';
echo '</p>';
echo '</div>';
echo '';
echo '<div class="container-sm py-5">';
echo '<div class="row">';
echo '<div class="col-md-4 custom-shadow">';
echo '<a';
echo 'href="https://alxs7.bemobtrcks.com/go/2d85b103-980c-443f-bdbd-44206d6e511f"';
echo '>';
echo '<img';
echo 'src="./asset/Image/LeanBiome -1-bottle.png"';
echo 'class="img-fluid custom-width-1"';
echo 'alt="LeanBiome -1-bottle"';
echo '/></a>';
echo '</div>';
echo '<div class="col-md-4 custom-shadow">';
echo '<a href="https://alxs7.bemobtrcks.com/go/2d85b103-980c-443f-bdbd-44206d6e511f">';
echo '<img';
echo 'src="./asset/Image/LeanBiome -6-bottle.png"';
echo 'class="img-fluid custom-width-1"';
echo 'alt="LeanBiome -6-bottle"';
echo '/></a>';
echo '</div>';
echo '<div class="col-md-4 custom-shadow">';
echo '<a href="https://alxs7.bemobtrcks.com/go/2d85b103-980c-443f-bdbd-44206d6e511f">';
echo '<img';
echo 'src="./asset/Image/LeanBiome -3-bottle.png"';
echo 'class="img-fluid custom-width-1"';
echo 'alt="LeanBiome -3-bottle"';
echo '/></a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="container-sm bg-warning custom-border">';
echo '<div class="row">';
echo '<div class="col-sm-2 custom-font-size">';
echo '<p class="text-center mb-0">';
echo '<i class="fa-solid fa-triangle-exclamation"></i>';
echo '</p>';
echo '</div>';
echo '<div class="col-sm-8 fs-3 pt-3">';
echo '<p>';
echo '<span class="fw-bold">WARNING:</span> Stock levels of LeanBiome ™ Bottle are limited Accept your reserved pouch above NOW before your discount expires.';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
?>